#!/usr/bin/env python3
from __future__ import annotations

import argparse
import importlib
import importlib.util
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if __package__ in (None, ""):
    sys.path.insert(0, str(ROOT))
    sys.path.insert(0, str(ROOT / "analysis"))
    sys.path.insert(0, str(ROOT / "track"))

from scripts.catalog_cli import (
    list_base_datasets,
    list_components,
    list_group_names,
    list_peak_names,
    list_prepare_targets,
    list_spectrasaves,
    DEFAULT_GROUPS_DIR,
    DEFAULT_PEAKS_DIR,
    TRACK_DATA_ROOT,
)


CACHE_PATH = ROOT / ".analysis" / "completion_cache.sh"

COMMAND_SPECS: dict[str, tuple[str, str]] = {
    "analysis/go/FFT.py": ("analysis.viz.see_fft_xya", "build_parser"),
    "analysis/go/Timeseries.py": ("analysis.viz.spacing_timeseries", "build_parser"),
    "analysis/go/Subtract.py": ("analysis.viz.see_config_subtract_xya", "build_parser"),
    "analysis/go/Logsubtract.py": ("analysis.viz.see_config_subtract_xya", "build_parser"),
    "analysis/go/Wavefunctions.py": ("analysis.go.Wavefunctions", "build_parser"),
    "analysis/go/ClickPeakFind.py": ("analysis.viz.click_peak_find", "build_parser"),
    "analysis/go/SpectrasaveView.py": ("analysis.viz.spectrasave_view", "build_parser"),
    "analysis/go/MakeGroup.py": ("analysis.go.MakeGroup", "build_parser"),
    "track/Bottom/0.VideoPrepareBottom.py": ("track.core.bottom_prepare", "build_parser"),
    "track/Bottom/1.TrackRun.py": ("track.core.bottom_run", "build_parser"),
    "track/Bottom/2.ProcessVerify.py": ("track.core.bottom_verify", "build_parser"),
    "track/Bottom/3.Label.py": ("track.core.bottom_label", "build_parser"),
    "track/Bottom/B0.BatchPrepare.py": ("track/Bottom/B0.BatchPrepare.py", "build_parser"),
    "track/Bottom/B1.BatchTrack.py": ("track/Bottom/B1.BatchTrack.py", "build_parser"),
    "track/Bottom/B2.BatchProcessVerify.py": ("track/Bottom/B2.BatchProcessVerify.py", "build_parser"),
}


def shell_quote(value: str) -> str:
    return "'" + value.replace("'", "'\"'\"'") + "'"


def load_module(module_name: str):
    if module_name.endswith(".py"):
        module_path = ROOT / module_name
        spec = importlib.util.spec_from_file_location(
            f"blocksssh_completion_{module_path.stem.replace('.', '_')}",
            module_path,
        )
        if spec is None or spec.loader is None:
            raise ImportError(f"Could not load module from {module_path}")
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        return module
    return importlib.import_module(module_name)


def action_takes_value(action: argparse.Action) -> bool:
    if isinstance(action, (argparse._StoreTrueAction, argparse._StoreFalseAction, argparse._HelpAction)):
        return False
    if getattr(action, "nargs", None) == 0:
        return False
    return True


def action_choices(action: argparse.Action) -> list[str]:
    choices = getattr(action, "choices", None)
    if choices is None:
        return []
    return [str(choice) for choice in choices]


def build_cache_text() -> str:
    lines: list[str] = [
        "# Autogenerated by scripts/build_completion_cache.py",
        "declare -A BLOCKSSSH_COMPLETION_OPTIONS=()",
        "declare -A BLOCKSSSH_COMPLETION_VALUE_OPTIONS=()",
        "declare -A BLOCKSSSH_COMPLETION_CHOICES=()",
        "declare -A BLOCKSSSH_COMPLETION_CATALOGS=()",
    ]

    catalog_entries = {
        "datasets": list_base_datasets(track_data_root=TRACK_DATA_ROOT),
        "prepare-targets": list_prepare_targets(),
        "groups": list_group_names(groups_dir=DEFAULT_GROUPS_DIR),
        "peaks": list_peak_names(peaks_dir=DEFAULT_PEAKS_DIR),
        "spectrasaves": list_spectrasaves(),
    }
    for key, values in catalog_entries.items():
        lines.append(
            f"BLOCKSSSH_COMPLETION_CATALOGS[{shell_quote(key)}]={shell_quote(' '.join(values))}"
        )

    for dataset in catalog_entries["datasets"]:
        lines.append(
            f"BLOCKSSSH_COMPLETION_CATALOGS[{shell_quote(f'components::{dataset}')}]="
            f"{shell_quote(' '.join(list_components(dataset)))}"
        )

    for command_key, (module_name, parser_fn_name) in COMMAND_SPECS.items():
        module = load_module(module_name)
        parser_fn = getattr(module, parser_fn_name)
        parser = parser_fn()
        if not isinstance(parser, argparse.ArgumentParser):
            raise TypeError(f"{module_name}:{parser_fn_name} did not return an ArgumentParser")

        option_strings: list[str] = []
        value_option_strings: list[str] = []
        choice_entries: list[tuple[str, list[str]]] = []
        for action in parser._actions:
            if not getattr(action, "option_strings", None):
                continue
            for option in action.option_strings:
                option_strings.append(str(option))
                if action_takes_value(action):
                    value_option_strings.append(str(option))
                choices = action_choices(action)
                if choices:
                    choice_entries.append((str(option), choices))

        option_strings = sorted(set(option_strings))
        value_option_strings = sorted(set(value_option_strings))
        lines.append(
            f"BLOCKSSSH_COMPLETION_OPTIONS[{shell_quote(command_key)}]={shell_quote(' '.join(option_strings))}"
        )
        lines.append(
            f"BLOCKSSSH_COMPLETION_VALUE_OPTIONS[{shell_quote(command_key)}]={shell_quote(' '.join(value_option_strings))}"
        )
        for option, choices in choice_entries:
            cache_key = f"{command_key}::{option}"
            lines.append(
                f"BLOCKSSSH_COMPLETION_CHOICES[{shell_quote(cache_key)}]={shell_quote(' '.join(choices))}"
            )

    return "\n".join(lines) + "\n"


def main() -> int:
    CACHE_PATH.parent.mkdir(parents=True, exist_ok=True)
    CACHE_PATH.write_text(build_cache_text(), encoding="utf-8", newline="\n")
    print(CACHE_PATH)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
